service: deflector-db

plugins:
  - serverless-deployment-bucket

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or falls back to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}
  keyStage:
    production: prod
    other: dev
  key: /fauna/resource-key-${
    self:custom.keyStage.${self:custom.stage}, self:custom.keyStage.other}

provider:
  name: aws
  runtime: nodejs12.x
  stage: edge
  region: ca-central-1
  deploymentBucket:
    name: deflector-deployment-${self:custom.stage}
    serverSideEncryption: AES256
  environment:
    STAGE: ${self:custom.stage}
  iamRoleStatements:
    # Copy the role statements to avoid errors
    ${ file( ../common/faunaRole.yml ) }

resources:
  Resources:
    ClassicPuzzles:
      Type: Custom::FaunaCollection
      Properties:
        ServiceToken: !ImportValue fauna-collection-lambda-arn
        CollectionName: classic-puzzles
        KeyParameterSecure: ${self:custom.key}
        Indexes:
          ClassicPuzzlesByTime:
            Name: classic-puzzles-by-time
            Values:
              - field:
                  - ts
                reverse: true
              - field:
                  - ref
